name: 'pushing-nuget-with-symbols'
description: 'Pushing your .csproj as nuget package with symbols.'
inputs:
  path:
    required: true
  apiKey:
    required: true
  dotnetVersion:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ inputs.dotnetVersion }}
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Pack with dotnet
      run: dotnet pack ${{ inputs.path }} --include-source --include-symbols -o Build --configuration Release
    - name: Push with dotnet
      run: dotnet nuget push "**/*.nupkg" -k ${{ inputs.apiKey }} --skip-duplicate -s https://api.nuget.org/v3/index.json 
