name: 'pushing-nuget-with-symbols'
description: 'Pushing your .csproj as nuget package with symbols.'
inputs:
  path:
    required: true
  api-key:
    required: true
  dotnet-version:
    required: true
    
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    - run: dotnet build ${{ inputs.path }} -c Release
      shell: bash
    - run: dotnet nuget push "**/*.nupkg" -k ${{ inputs.api-key }} --skip-duplicate -s https://api.nuget.org/v3/index.json 
      shell: bash
